/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.challenge;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.NoSuchElementException;

import java.time.LocalDate;

public class BootcampTest {
    private String title = "Back-end Java";
    private String description = "Back-end Java bootcamp";

    private Bootcamp bootcamp = new Bootcamp(title, description);
    private Content content = new Course(title, description, 40);

    @Test
    public void getName() {
        assertEquals(title, bootcamp.getName());
    }

    @Test
    public void setName() {
        String newTitle = "Front-end Java";
        bootcamp.setName(newTitle);

        assertEquals(newTitle, bootcamp.getName());
    }

    @Test
    public void getDescription() {
        assertEquals(description, bootcamp.getDescription());
    }

    @Test
    public void getInitialDate() {
        LocalDate initialDate = LocalDate.now();

        assertEquals(initialDate, bootcamp.getInitialDate());
    }

    @Test
    public void getEndDate() {
        LocalDate endDate = LocalDate.now().plusDays(45);

        assertEquals(endDate, bootcamp.getEndDate());
    }

    @Test
    public void addAndGetContent() {
        bootcamp.addContent(content);
        assertTrue(bootcamp.getContents().contains(content));
    }

    @Test
    public void removeContent() {
        assertTrue(bootcamp.getContents().contains(content));
        bootcamp.removeContent(content);
        assertTrue(bootcamp.getContents().isEmpty());
    }

    @Test
    public void removeContentFromEmptySet() {
        assertThrows(NoSuchElementException.class, () -> bootcamp.removeContent(content));
    }
}
