/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.challenge;

import org.junit.Test;
import static org.junit.Assert.*;

public class CourseTest {
    private String title = "Java";
    private String description = "Java course";
    private int workload = 40;

    private Course course = new Course(title, description, workload);

    @Test
    public void computeXp() {
        double expectedXp = workload * 10d;
        double xp = course.computeXp();

        assertEquals(expectedXp, xp, 0.01);
    }

    @Test
    public void getWorkload() {
        assertEquals(workload, course.getWorkload());
    }

    @Test
    public void setWorkload() {
        int newWorkload = 80;
        course.setWorkload(newWorkload);

        assertEquals(newWorkload, course.getWorkload());
    }
}
