/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.challenge;

import org.junit.Test;
import static org.junit.Assert.*;

public class DeveloperTest {
    private String title = "Java";
    private String description = "Java course";
    
    private Bootcamp bootcamp = new Bootcamp(title, description);
    private Developer dev = new Developer("Developer");

    @Test public void signUp() {
        dev.signUp(bootcamp);
        assertTrue(bootcamp.getSubscribedDevelopers().contains(dev));
    }

    @Test public void computeTotalXp() {
        assertEquals(0.0, dev.computeTotalXp(), 0.01);
    }
    
}
