/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.challenge;

import org.junit.Test;
import static org.junit.Assert.*;

import java.time.LocalDate;

public class MentorshipTest {
    private String title = "Mentoria Java";
    private String description = "Descrição mentoria Java";
    private LocalDate date = LocalDate.now();

    private Mentorship mentorship = new Mentorship(title, description, date);

    @Test
    public void computeXp() {
        double expectedXp = 30d;
        double xp = mentorship.computeXp();

        assertEquals(expectedXp, xp, 0.01);
    }

    @Test
    public void getDate() {
        assertEquals(date, mentorship.getDate());
    }

    @Test
    public void setDate() {
        LocalDate newDate = LocalDate.now().plusDays(5);
        mentorship.setDate(newDate);

        assertEquals(newDate, mentorship.getDate());
    }
}
